# Generated by Django 4.2.1 on 2023-05-04 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_tasks_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='In_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='dead_line',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 12, 56, 1, 129996, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
